# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('old_price', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=60)),
                ('size', models.CharField(choices=[('XL', 'Extra_large'), ('Lg', 'large'), ('md', 'medium'), ('sm', 'small')], default='md', max_length=2)),
                ('specifications', models.TextField()),
                ('thumbnail', models.FileField(upload_to=b'')),
                ('image', models.FileField(upload_to=b'')),
                ('description', models.TextField()),
                ('Label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Label')),
            ],
        ),
    ]
